/* ═══════════════════════════════════════════════
   constants.js — 共享状态常量
   所有模块引用这些常量，杜绝硬编码字符串
   ═══════════════════════════════════════════════ */

var STATUS = {
  AVAILABLE: 'available',
  PREPARING: 'preparing',
  TRANSLATING: 'translating',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELED: 'canceled',
};

var MESSAGE_TYPE = {
  GET_VIDEO_TASKS: 'GET_VIDEO_TASKS',
  START_VIDEO_TASK: 'START_VIDEO_TASK',
  CANCEL_VIDEO_TASK: 'CANCEL_VIDEO_TASK',
  OPEN_VIDEO_TASK: 'OPEN_VIDEO_TASK',
  DETECT_VIDEO_TRANSLATABLE: 'DETECT_VIDEO_TRANSLATABLE',
  PREPARE_VIDEO_TRANSLATION: 'PREPARE_VIDEO_TRANSLATION',
  START_SUBTITLE_TRANSLATION: 'START_SUBTITLE_TRANSLATION',
  APPLY_VIDEO_TRANSLATIONS: 'APPLY_VIDEO_TRANSLATIONS',
  VIDEO_TASK_PROGRESS: 'VIDEO_TASK_PROGRESS',
  VIDEO_TASK_GROUP_TRANSLATED: 'VIDEO_TASK_GROUP_TRANSLATED',
  TRANSLATE_TEXT: 'TRANSLATE_TEXT',
  TRANSLATE_BATCH: 'TRANSLATE_BATCH',
  CACHE_GET: 'CACHE_GET',
  CACHE_SET: 'CACHE_SET',
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTING: 'UPDATE_SETTING',
  PROXY_FETCH: 'PROXY_FETCH',
  DEBUG_LOG: 'DEBUG_LOG',
  GET_DEBUG_LOGS: 'GET_DEBUG_LOGS',
  CLEAR_DEBUG_LOGS: 'CLEAR_DEBUG_LOGS',
};
